import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PlanGraph } from "@/components/PlanGraph";
import { PerformanceTrend } from "@/components/PerformanceTrend";
import { trpc } from "@/lib/trpc";
import type { QueryLensAnalysis } from "../../../server/querylensAnalysis";
import { Activity, AlertTriangle, BarChart3, BookOpen, Bot, ChevronRight, CircleDot, ClipboardList, Code2, Database, FileSearch, Gauge, History, LayoutDashboard, Loader2, Network, Play, Plus, Search, Settings2, ShieldCheck, Sparkles, Table2, WandSparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const starterQuery = `SELECT o.id, o.created_at, c.email, p.status
FROM orders o
JOIN customers c ON c.id = o.customer_id
LEFT JOIN payments p ON p.order_id = o.id
WHERE o.created_at >= CURRENT_DATE - INTERVAL '30 days'
  AND o.status = 'completed'
ORDER BY o.created_at DESC;`;

const severityStyle = {
  critical: "border-rose-200 bg-rose-50 text-rose-700",
  warning: "border-amber-200 bg-amber-50 text-amber-700",
  info: "border-indigo-200 bg-indigo-50 text-indigo-700",
};

export default function Home() {
  const [sql, setSql] = useState(starterQuery);
  const [analysis, setAnalysis] = useState<QueryLensAnalysis>();
  const utils = trpc.useUtils();
  const analyzeMutation = trpc.queryLens.analyze.useMutation({
    onSuccess: result => {
      setAnalysis(result);
      utils.queryLens.history.invalidate();
      toast.success("Analysis complete", { description: "A new plan comparison and optimization diagnosis are ready." });
    },
    onError: error => toast.error("Analysis unavailable", { description: error.message }),
  });
  const history = trpc.queryLens.history.useQuery({ limit: 24 });
  const historyRows = history.data ?? [];
  const runAnalysis = () => analyzeMutation.mutate({ sql });

  return (
    <div className="min-h-screen bg-[#f4f6fa] text-slate-950">
      <header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b border-slate-200 bg-white px-5 shadow-[0_1px_0_rgba(15,23,42,.02)]">
        <div className="flex items-center gap-4"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-white shadow-lg shadow-slate-300"><Search className="h-4 w-4" /></div><div className="border-r border-slate-200 pr-4"><p className="font-bold tracking-tight">QueryLens</p><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">Performance console</p></div><div className="hidden items-center gap-2 text-sm text-slate-500 md:flex"><span className="font-medium text-slate-800">Workspace</span><ChevronRight className="h-3.5 w-3.5" /><span>Query analysis</span></div></div>
        <div className="flex items-center gap-2"><Badge variant="outline" className="hidden border-emerald-200 bg-emerald-50 text-emerald-700 sm:flex"><span className="mr-1.5 h-1.5 w-1.5 rounded-full bg-emerald-500" />Engine online</Badge><Button variant="outline" size="sm" className="border-slate-200 text-slate-600"><BookOpen className="mr-2 h-3.5 w-3.5" />Documentation</Button><Button size="sm" className="bg-slate-950 text-white hover:bg-slate-800" onClick={() => { setSql(starterQuery); setAnalysis(undefined); }}><Plus className="mr-1.5 h-3.5 w-3.5" />New analysis</Button></div>
      </header>

      <div className="flex min-h-[calc(100vh-4rem)]">
        <aside className="hidden w-[76px] shrink-0 border-r border-slate-200 bg-white py-5 lg:flex lg:flex-col lg:items-center lg:justify-between"><nav className="flex flex-col gap-2"><RailItem icon={<LayoutDashboard />} label="Console" active /><RailItem icon={<History />} label="History" /><RailItem icon={<Table2 />} label="Schema" /><RailItem icon={<Activity />} label="Monitoring" /></nav><nav className="flex flex-col gap-2"><RailItem icon={<Bot />} label="Assistant" /><RailItem icon={<Settings2 />} label="Settings" /></nav></aside>

        <main className="min-w-0 flex-1 px-4 py-5 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-[1500px]">
            <section className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-indigo-600"><CircleDot className="h-3.5 w-3.5" /> Active inspection</div><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.04em] text-slate-950">Query diagnosis</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Interrogate query shape, surface high-cost operators, and compare the fastest defensible path without executing source data.</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs text-slate-500 shadow-sm"><ShieldCheck className="h-4 w-4 text-emerald-600" /> Read-only analysis <span className="text-slate-300">·</span> PostgreSQL semantics</div></section>

            <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
              <section className="space-y-5">
                <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                  <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-3"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-indigo-50 text-indigo-700"><Code2 className="h-4 w-4" /></div><div><p className="text-sm font-bold text-slate-900">Untitled analysis</p><p className="text-xs text-slate-400">Draft query · auto-normalized on run</p></div></div><div className="flex items-center gap-2"><Badge variant="outline" className="border-slate-200 bg-slate-50 font-mono text-[10px] text-slate-600">PostgreSQL</Badge><Badge variant="outline" className="border-slate-200 bg-slate-50 font-mono text-[10px] text-slate-600">Estimated mode</Badge></div></div>
                  <div className="bg-slate-950 p-3"><textarea value={sql} onChange={event => setSql(event.target.value)} spellCheck={false} aria-label="SQL query input" className="font-mono min-h-[300px] w-full resize-y rounded-xl border border-slate-800 bg-slate-950 p-4 text-[13px] leading-6 text-slate-100 outline-none transition focus:border-indigo-400 focus:ring-4 focus:ring-indigo-400/15" /></div>
                  <div className="flex flex-col gap-3 border-t border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-xs text-slate-500"><FileSearch className="h-4 w-4 text-indigo-600" /> Parses SELECT, WITH, and EXPLAIN statements only.</div><div className="flex gap-2"><Button variant="outline" className="border-slate-200 text-slate-600" onClick={() => { setSql(starterQuery); setAnalysis(undefined); }}>Reset</Button><Button onClick={runAnalysis} disabled={analyzeMutation.isPending} className="bg-indigo-600 font-bold text-white shadow-md shadow-indigo-200 hover:bg-indigo-700">{analyzeMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Play className="mr-2 h-4 w-4 fill-current" />}Run diagnosis</Button></div></div>
                </div>

                {!analysis ? <EmptyAnalysisState /> : <AnalysisResults analysis={analysis} />}
              </section>

              <aside className="space-y-5 xl:sticky xl:top-[84px] xl:self-start">
                <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Inspection status</p><h2 className="mt-1 text-lg font-bold tracking-tight">Analysis pipeline</h2></div><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Network className="h-4 w-4" /></div></div><div className="mt-5 space-y-1"><PipelineStep number="01" title="Parse SQL structure" detail="Relations, predicates & joins" active /><PipelineStep number="02" title="Model operator cost" detail="Estimate plan shape" active={Boolean(analysis)} /><PipelineStep number="03" title="Rank interventions" detail="Indexes, joins & operators" active={Boolean(analysis)} /><PipelineStep number="04" title="Compare outcomes" detail="Baseline vs. optimized" active={Boolean(analysis)} /></div></div>
                <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Current context</p><div className="mt-4 space-y-3"><ContextRow icon={<Database />} label="Target dialect" value="PostgreSQL" /><ContextRow icon={<Gauge />} label="Prediction model" value={analysis?.model ?? "Waiting for query"} /><ContextRow icon={<BarChart3 />} label="Benchmark mode" value={analysis ? "Estimated" : "Not started"} /></div></div>
                {analysis && <div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-5"><div className="flex items-start gap-3"><div className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-indigo-600 text-white"><Sparkles className="h-4 w-4" /></div><div><p className="font-bold text-indigo-950">Diagnosis ready</p><p className="mt-1 text-xs leading-5 text-indigo-800">{analysis.recommendations.length} prioritized actions and {analysis.operatorFindings.length} operator signals are available below.</p></div></div></div>}
              </aside>
            </div>

            <section className="mt-5 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-slate-200 px-5 py-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-slate-400"><History className="h-3.5 w-3.5" /> Recorded analyses</div><h2 className="mt-1 text-lg font-bold tracking-tight">Performance history</h2></div><span className="text-xs text-slate-400">{historyRows.length} saved runs</span></div>{historyRows.length ? <div className="p-5"><PerformanceTrend points={historyRows} /><div className="mt-5 divide-y divide-slate-100 rounded-xl border border-slate-100">{historyRows.slice(0, 4).map(row => <div className="flex items-center justify-between gap-4 px-4 py-3" key={row.id}><p className="min-w-0 truncate font-mono text-xs text-slate-600">{row.sql.replace(/\s+/g, " ")}</p><div className="flex shrink-0 items-center gap-4 text-xs"><span className="text-slate-400">{row.complexity}</span><span className="font-bold text-emerald-600">{Math.round((1 - row.optimizedLatencyMs / row.baselineLatencyMs) * 100)}% faster</span></div></div>)}</div></div> : <div className="flex flex-col items-center justify-center px-5 py-12 text-center"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-500"><ClipboardList className="h-4 w-4" /></div><p className="mt-3 text-sm font-bold text-slate-700">No diagnosis history yet</p><p className="mt-1 text-xs text-slate-400">Run the inspection above to begin building a performance trail.</p></div>}</section>
          </div>
        </main>
      </div>
    </div>
  );
}

function AnalysisResults({ analysis }: { analysis: QueryLensAnalysis }) {
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Complexity" value={`${analysis.complexity.label} · ${analysis.complexity.score}`} detail={`${analysis.queryShape.tables.length} tables · ${analysis.queryShape.joinCount} joins`} icon={<Gauge />} tone="indigo" /><Metric label="Baseline cost" value={analysis.baselinePlan.totalCost.toLocaleString()} detail="estimated plan units" icon={<BarChart3 />} tone="slate" /><Metric label="Cost reduction" value={`${analysis.benchmark.costReductionPercent}%`} detail="optimized path estimate" icon={<Activity />} tone="emerald" /><Metric label="Latency delta" value={`${analysis.benchmark.latencyReductionPercent}%`} detail={`${analysis.benchmark.baselineLatencyMs}ms → ${analysis.benchmark.optimizedLatencyMs}ms`} icon={<Sparkles />} tone="amber" /></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Operator comparison</p><h2 className="mt-1 text-xl font-bold tracking-tight">Baseline against optimized plan</h2></div><div className="flex flex-wrap gap-2"><Badge className="border border-rose-200 bg-rose-50 text-rose-700">Baseline · {analysis.baselinePlan.totalCost.toLocaleString()}</Badge><Badge className="border border-indigo-200 bg-indigo-50 text-indigo-700">Optimized · {analysis.optimizedPlan.totalCost.toLocaleString()}</Badge></div></div><div className="mt-5 grid gap-4 2xl:grid-cols-2"><PlanGraph title="Baseline operators" nodes={analysis.baselinePlan.nodes} accent="pink" /><PlanGraph title="Optimized operators" nodes={analysis.optimizedPlan.nodes} accent="violet" /></div><div className="mt-4 flex items-start gap-2 rounded-lg bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-500"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-500" />{analysis.benchmark.method}</div></section>
    <div className="grid gap-5 2xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><PanelTitle kicker="Ranked interventions" title="Recommended next moves" value={`${analysis.recommendations.length} findings`} /><div className="mt-4 space-y-3">{analysis.recommendations.map(item => <article className="rounded-xl border border-slate-200 p-4" key={`${item.priority}-${item.title}`}><div className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-slate-100 text-xs font-bold text-slate-600">{item.priority}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-bold text-slate-900">{item.title}</h3><Badge className={severityStyle[item.severity]}>{item.severity} · {item.estimatedImpact}%</Badge></div><p className="mt-2 text-sm leading-6 text-slate-500">{item.detail}</p><code className="mt-3 block overflow-x-auto rounded-lg bg-slate-950 px-3 py-2 font-mono text-[11px] leading-5 text-indigo-100">{item.action}</code></div></div></article>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><PanelTitle kicker="Plan pressure" title="Expensive operator signals" value={`${analysis.operatorFindings.length} signals`} /><div className="mt-4 space-y-3">{analysis.operatorFindings.map(item => <div className="rounded-xl border border-slate-200 bg-slate-50 p-4" key={item.title}><div className="flex items-start gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-amber-100 text-amber-700"><AlertTriangle className="h-4 w-4" /></div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold text-slate-800">{item.title}</p><span className="text-xs font-bold text-amber-700">{item.estimatedImpact}% impact</span></div><p className="mt-1.5 text-xs leading-5 text-slate-500">{item.detail}</p></div></div></div>)}</div><div className="mt-5 rounded-xl border border-indigo-100 bg-indigo-50 p-4"><p className="text-xs font-bold text-indigo-950">Normalized PostgreSQL</p><pre className="font-mono mt-2 max-h-40 overflow-auto whitespace-pre-wrap text-[11px] leading-5 text-indigo-900/75">{analysis.normalizedSql}</pre></div></section></div></div>;
}

function EmptyAnalysisState() { return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid min-h-[260px] md:grid-cols-[.85fr_1.15fr]"><div className="flex flex-col justify-center border-b border-slate-200 bg-slate-50 p-7 md:border-b-0 md:border-r"><div className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-600 text-white"><WandSparkles className="h-5 w-5" /></div><p className="mt-5 text-lg font-bold tracking-tight">Your query is staged.</p><p className="mt-2 max-w-xs text-sm leading-6 text-slate-500">Run the diagnosis to build an estimated plan tree and expose the specific work PostgreSQL is likely to perform.</p></div><div className="p-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">What will be inspected</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><MiniInspect icon={<Network />} title="Plan shape" detail="Scan, join, sort, and aggregate relationships." /><MiniInspect icon={<Gauge />} title="Cost pressure" detail="Complexity factors and high-cost operator signals." /><MiniInspect icon={<Table2 />} title="Index opportunities" detail="Predicates that could avoid relation scans." /><MiniInspect icon={<Activity />} title="Outcome delta" detail="Estimated baseline and optimization effects." /></div></div></div></section>; }

function RailItem({ icon, label, active = false }: { icon: React.ReactNode; label: string; active?: boolean }) { return <button aria-label={label} title={label} className={`grid h-10 w-10 place-items-center rounded-xl transition ${active ? "bg-slate-950 text-white shadow-md" : "text-slate-400 hover:bg-slate-100 hover:text-slate-700"}`}>{icon}</button>; }
function PipelineStep({ number, title, detail, active }: { number: string; title: string; detail: string; active: boolean }) { return <div className="flex gap-3 py-2"><div className={`grid h-7 w-7 shrink-0 place-items-center rounded-lg text-[10px] font-extrabold ${active ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-400"}`}>{number}</div><div><p className={`text-sm font-semibold ${active ? "text-slate-800" : "text-slate-500"}`}>{title}</p><p className="mt-0.5 text-xs text-slate-400">{detail}</p></div></div>; }
function ContextRow({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3"><span className="text-slate-400">{icon}</span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-slate-400">{label}</p><p className="truncate text-sm font-semibold text-slate-700">{value}</p></div></div>; }
function Metric({ label, value, detail, icon, tone }: { label: string; value: string; detail: string; icon: React.ReactNode; tone: "indigo" | "slate" | "emerald" | "amber" }) { const tones = { indigo: "bg-indigo-50 text-indigo-700", slate: "bg-slate-100 text-slate-700", emerald: "bg-emerald-50 text-emerald-700", amber: "bg-amber-50 text-amber-700" }; return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-slate-500">{label}</p><span className={`grid h-7 w-7 place-items-center rounded-lg ${tones[tone]}`}>{icon}</span></div><p className="mt-4 text-2xl font-extrabold tracking-tight text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div>; }
function PanelTitle({ kicker, title, value }: { kicker: string; title: string; value: string }) { return <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">{kicker}</p><h2 className="mt-1 text-xl font-bold tracking-tight text-slate-900">{title}</h2></div><Badge variant="outline" className="border-slate-200 bg-slate-50 text-slate-600">{value}</Badge></div>; }
function MiniInspect({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="flex gap-3"><span className="mt-0.5 text-indigo-600">{icon}</span><div><p className="text-sm font-bold text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div></div>; }
